## Using pandas to Load and Preprocess

From: https://www.tensorflow.org/tutorials/load_data/pandas_dataframe

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

16384/13273 [=====================================] - 0s 1us/step


In [3]:
df = pd.read_csv(csv_file)
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [6]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

In [7]:
target = df.pop('target')

In [18]:
# So yeah, the input values are supposed to have the ouput values here
print(len(df))
print(len(target))

print(df.columns)
print(target)

303
303
Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')
0      0
1      1
2      0
3      0
4      0
      ..
298    0
299    1
300    1
301    1
302    1
Name: target, Length: 303, dtype: int64


In [19]:
# Combine input values with targets into a tensorflow dataset
# End up with with ( 300x[NxM], 300x[1]). You know, if that makes any sense
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [20]:
#How input and target out put
for feat, targ in dataset.take(5):
    print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [27]:
# WTF is this? - Creates a constant tensor from a tensor-like object (series)
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

In [28]:
# shuffle the data, create a batch of size one.
train_dataset = dataset.shuffle(len(df)).batch(1)

In [34]:
def get_compiled_model():
    """
    Creates the model, compiles the model and returns it
    """
    # Basic configuration of the model
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(10, activation='relu'),
        tf.keras.layers.Dense(1)
    ])
        
    # Configures the built model with given inputs.
    model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
    
    return model

In [35]:
# Create the model and train it using "fit" method
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15
303/303 [==============================] - 2s 3ms/step - loss: 3.7325 - accuracy: 0.5451
Epoch 2/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6460 - accuracy: 0.7425
Epoch 3/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5941 - accuracy: 0.7586
Epoch 4/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6422 - accuracy: 0.7157
Epoch 5/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5758 - accuracy: 0.7309
Epoch 6/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5703 - accuracy: 0.7598
Epoch 7/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5483 - accuracy: 0.7668
Epoch 8/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5788 - accuracy: 0.7183
Epoch 9/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5701 - accuracy: 0.7570
Epoch 10/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5863 - accuracy: 0.6755

### Do something similar but with dictionaryies.... becase we can?

In [36]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [38]:
inputs.keys()

dict_keys(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'])

In [39]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [40]:
for dict_slice in dict_slices.take(1):
    print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57])>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1])>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3])>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150])>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168])>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0])>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0])>, 'thalach': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([150, 108, 129, 187, 172, 178, 160, 163, 147, 155, 148, 153, 142,
  

In [41]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 2s 3ms/step - loss: 3.8863 - accuracy: 0.7493
Epoch 2/15
19/19 [==============================] - 0s 3ms/step - loss: 1.2110 - accuracy: 0.6988
Epoch 3/15
19/19 [==============================] - 0s 3ms/step - loss: 0.8948 - accuracy: 0.6685
Epoch 4/15
19/19 [==============================] - 0s 3ms/step - loss: 0.7816 - accuracy: 0.6830
Epoch 5/15
19/19 [==============================] - 0s 3ms/step - loss: 0.7025 - accuracy: 0.7082
Epoch 6/15
19/19 [==============================] - 0s 3ms/step - loss: 0.6558 - accuracy: 0.7083
Epoch 7/15
19/19 [==============================] - 0s 4ms/step - loss: 0.6219 - accuracy: 0.7206
Epoch 8/15
19/19 [==============================] - 0s 2ms/step - loss: 0.5930 - accuracy: 0.7356
Epoch 9/15
19/19 [==============================] - 0s 5ms/step - loss: 0.5698 - accuracy: 0.7480
Epoch 10/15
19/19 [==============================] - 0s 5ms/step - loss: 0.5504 - accuracy: 0.7629
Epoch 11/15
19/19 [